<?php $this->start('head'); ?>
<?php $this->end() ?>

<?php $this->start('body') ?>

<section class="section fixed-section">

    <h1 class="title has-text-centered">Posted Comments</h1>

    <table class="table is-fullwidth">
        <thead>
            <tr>
                <th>Id</th>
                <th>User Name</th>
                <th>Email Address</th>
                <th>Content</th>
                <th>Date Creation</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($this->item('comments')) : ?>

                <?php foreach ($this->item('comments') as $key => $value) : ?>

                    <tr>
                        <th><?= $value->id ?></th>
                        <td><?= $value->name ?></td>
                        <td><?= $value->email ?></td>
                        <td><?= $value->text ?></td>
                        <td><?= $value->created_at ?></td>
                        <td><?= $value->approved ? 'Approved' : 'Pending' ?></td>

                        <td>
                            <?php if (!$value->approved) : ?>
                                <form action="<?= BASE_URL . '/admin/approve' ?>" method="post">
                                    <div class="field">
                                        <div class="control">
                                            <input type="hidden" name="comment_id" value="<?= $value->id ?>">
                                            <button class="button is-primary ">
                                                Approve
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            <?php endif; ?>

                        </td>


                    </tr>
                <?php endforeach; ?>

            <?php else : ?>

                <h1 class="sub-title has-text-centered">There is no posted comment</h1>

            <?php endif; ?>
        </tbody>
    </table>
</section>

<?php $this->end() ?>