<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="<?= BASE_URL . '/home' ?>">
            <img src="<?= asset('img/logo.jpg') ?>">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="<?= BASE_URL . '/home' ?>">
                Home / Catalog
            </a>
            <?php if ($this->item('auth_user')) : ?>
                <a class="navbar-item" href="<?= BASE_URL . '/admin' ?>">
                    Admin Panel
                </a>
            <?php endif ?>

        </div>

        <div class="navbar-end">
            <?php if ($this->item('auth_user')) : ?>

                <div class="navbar-item">
                    <?= $this->item('auth_user')->name ?>
                </div>


            <?php endif ?>

            <div class="navbar-item">
                <div class="buttons">
                    <?php if ($this->item('auth_user')) : ?>

                        <a class="button is-light" href="<?= BASE_URL . '/auth/logout' ?>">
                            Log out
                        </a>

                    <?php else : ?>
                        <a class="button is-primary" href="<?= BASE_URL . '/auth' ?>">
                            Log in
                        </a>

                    <?php endif ?>

                </div>
            </div>
        </div>
    </div>
</nav>